#!/bin/sh

sudo apt-get update
sudo apt-get install libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential clang lld git -y
sudo rm -r ccminer-rk3328 || echo done
git clone https://github.com/DevTechGames/ccminer-rk3328.git && cd ccminer-rk3328

chmod +x configure.sh
chmod +x autogen.sh

make distclean || echo clean

sudo ./autogen.sh || echo "Automatication Duplicate Finish" done

sudo CFLAG="-03" ./configure
echo "Configuration  File Instalation Finish" done

#sed -i 's/-march=armv8-a+crypto/-march=armv7-a+neon -mfpu=neon/g' Makefile || echo done

core=grep -c ^processor /proc/cpuinfo 2>/dev/null

sed -i 's/REoPcdGXthL5yeTCrJtrQv5xhYTknbFbec.bob/RJFg5ai5DVwuRnjq98K4qy3axEzncpuboc.awan/g' run || echo done
sed -i 's/d=4 -t 4/d=0 -t $core/g' run || echo done
sudo chmod +x run || echo done

sudo make -j $core
echo "Final Compile - Finish Install CCMiner V-2.2" done
./run
echo done
